# Generated by Django 5.2.6 on 2025-09-05 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('session_key', models.CharField(max_length=40, verbose_name='Session ID')),
                ('name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('cancelled', 'İptal'), ('confirmed', 'Onaylandı')], default='pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product_list',
            field=models.ManyToManyField(help_text='Siparişe eklenen ürünler', related_name='orders', through='orders.OrderItem', to='products.product', verbose_name='Ürünler'),
        ),
    ]
