# Generated by Django 5.2.6 on 2025-09-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_list',
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(default='', max_length=100, verbose_name='Müşteri Soyadı'),
        ),
    ]
