# Generated by Django 5.2.6 on 2025-09-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_product_list_order_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Müşteri Soyadı'),
        ),
    ]
