# Generated by Django 5.2.6 on 2025-09-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='surname',
        ),
    ]
