# Generated by Django 5.2.6 on 2025-09-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='WhatsApp Telefon Numarası')),
                ('phone_number', models.CharField(help_text='Format: +90xxxxxxxxxx', max_length=13, unique=True, verbose_name='Telefon Numarası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'İletişim Ayarı',
                'verbose_name_plural': 'İletişim Ayarları',
            },
        ),
    ]
