# Generated by Django 5.2.6 on 2025-09-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnumber',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='contactnumber',
            name='phone_number',
            field=models.CharField(help_text='Format: +90xxxxxxxxxx', max_length=13, unique=True, verbose_name='WhatsApp Telefon Numarası'),
        ),
    ]
