# Generated by Django 5.2.6 on 2025-09-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_alter_contactnumber_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnumber',
            name='phone_number',
            field=models.CharField(help_text='Format: + 90xxxxxxxxxx', max_length=13, unique=True, verbose_name='WhatsApp Telefon Numarası'),
        ),
    ]
